apiVersion: v1 
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
spec:
  storageClassName: nodestorage
  capacity:
    storage: 10Gi #we are consuming 10gi of storage. but this is thin provisioning. 
  accessModes: 
      - ReadWriteMany 
  hostPath:
      path: /mnt/data